version: '3.8'
services:
  backend:
    image: jmfantasyfootball.azurecr.io/backend:v4
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
    ports:
      - "5000:5000"

  frontend:
    image: jmfantasyfootball.azurecr.io/frontend:v4
    restart: always
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "80:80"
